name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-minify-plugin mkdocstrings pymdown-extensions
      
      - name: Build docs
        run: mkdocs build --strict
      
      - name: Check links
        run: |
          pip install linkchecker
          linkchecker --check-extern site/
      
      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          clean: true
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install markdownlint-cli yamllint
      
      - name: Lint Markdown files
        run: markdownlint '**/*.md' --ignore node_modules
      
      - name: Lint YAML files
        run: yamllint -c .yamllint .
      
      - name: Create .yamllint if not exists
        run: |
          if [ ! -f .yamllint ]; then
            echo "extends: default" > .yamllint
            echo "rules:" >> .yamllint
            echo "  line-length: disable" >> .yamllint
          fi 