name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # 毎週日曜日に実行

jobs:
  cargo-audit:
    name: Rust Dependencies Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install cargo-audit
        run: cargo install cargo-audit
      
      - name: Run cargo-audit
        run: cargo audit
  
  trivy-scan:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t mcp-security-gateway:${{ github.sha }} .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'mcp-security-gateway:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
      
      - name: Run Trivy for Dockerfile
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

# CodeQLはRustをサポートしていないため、このジョブは無効化されています
# codeql-scan:
#   name: CodeQL Analysis
#   runs-on: ubuntu-latest
#   permissions:
#     security-events: write
#   steps:
#     - uses: actions/checkout@v4
#     
#     - name: Initialize CodeQL
#       uses: github/codeql-action/init@v3
#       with:
#         languages: 'cpp'
#     
#     - name: Install dependencies
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y protobuf-compiler bubblewrap libseccomp-dev
#     
#     - name: Build with Cargo
#       run: cargo build
#     
#     - name: Perform CodeQL Analysis
#       uses: github/codeql-action/analyze@v3 